[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools",
  "wheel",
  "scikit-build>=0.17.0",
  "cmake>=3.20",
  "pybind11>=2.11.0",
]

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = [
  "tests",
]

[tool.cibuildwheel]
build = ["cp38-*", "cp39-*", "cp310-*", "cp311-*"]
build-frontend = "build"
build-verbosity = 1
test-command = "pytest {project}/tests/test_import.py"
test-requires = ["numpy", "pytest", "pytest-cov", "pytest-benchmark"]

[tool.cibuildwheel.linux]
before-all = ["bash {package}/scripts/build-opencl-linux.sh"]
repair-wheel-command = "auditwheel show {wheel} && auditwheel repair --lib-sdir .libs -w {dest_dir} {wheel}"
skip = ["cp27-*", "cp36-*", "pp*", "*-musllinux*", "*_i686"]

#[[tool.cibuildwheel.overrides]]
#select = "*-musllinux*"
#before-all = [
#    "apk add ruby",
#    "bash {package}/scripts/build-ocl.sh",
#]

[tool.cibuildwheel.windows]
before-all = "bash {package}/scripts/build-opencl-windows.sh"
environment = {SKBUILD_CONFIGURE_OPTIONS = "-DOpenCL_LIBRARIES:FILEPATH='C:/Program Files/OpenCL-ICD-Loader/lib/OpenCL.lib' -DOpenCL_INCLUDE_DIRS:PATH='C:/Program Files/OpenCL-ICD-Loader/include/'"}
skip = ["cp27-*", "cp36-*", "pp*", "*-win32"]

[tool.cibuildwheel.macos]
environment = {MACOSX_DEPLOYMENT_TARGET = '10.14'}
skip = ["cp27-*", "cp36-*", "pp*", "*_universal2"]
